# Generated by Django 4.2.3 on 2023-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('prompt', models.TextField(max_length=500)),
                ('price', models.FloatField(max_length=30)),
            ],
        ),
    ]
