# Generated by Django 4.2.3 on 2023-07-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompts',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='prompt',
            field=models.TextField(max_length=5000),
        ),
    ]
