# Generated by Django 4.2.3 on 2023-07-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mps_app.prompts'),
        ),
        migrations.AddField(
            model_name='users',
            name='prompts',
            field=models.ManyToManyField(to='mps_app.prompts'),
        ),
    ]
