# Generated by Django 4.2.3 on 2023-07-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0002_payment_prompt_users_prompts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.TextField()),
            ],
        ),
    ]
