# Generated by Django 4.2.3 on 2023-07-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0004_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pending',
            field=models.ManyToManyField(related_name='pending', to='mps_app.prompts'),
        ),
    ]
