# Generated by Django 4.2.3 on 2023-07-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0004_buyers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Users',
        ),
        migrations.DeleteModel(
            name='Buyers',
        ),
        migrations.AddField(
            model_name='prompts',
            name='name',
            field=models.TextField(default='NULL', max_length=30),
        ),
    ]
