# Generated by Django 4.2.3 on 2023-07-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0005_rename_sellers_users_delete_buyers_prompts_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
