# Generated by Django 4.2.3 on 2023-07-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0005_users_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='posted',
            field=models.ManyToManyField(related_name='posted', to='mps_app.prompts'),
        ),
    ]
