# Generated by Django 4.2.3 on 2023-07-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0006_users_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
