# Generated by Django 4.2.3 on 2023-07-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0007_payment_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='sales',
        ),
        migrations.AddField(
            model_name='prompts',
            name='sales',
            field=models.IntegerField(default=0),
        ),
    ]
