# Generated by Django 4.2.3 on 2023-07-25 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0008_remove_payment_sales_prompts_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='mps_app.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='prompts',
            field=models.ManyToManyField(related_name='prompts', to='mps_app.prompts'),
        ),
    ]
