# Generated by Django 4.2.3 on 2023-07-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0011_pay_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
