# Generated by Django 4.2.3 on 2023-07-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0013_users_from_affiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_affiliate',
            field=models.TextField(default='no'),
        ),
    ]
