# Generated by Django 4.2.3 on 2023-07-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0014_users_is_affiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='link',
            field=models.TextField(default='null'),
        ),
    ]
