# Generated by Django 4.2.3 on 2023-08-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0015_users_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='payment_id',
            field=models.TextField(default='null', max_length=50),
        ),
    ]
