# Generated by Django 4.2.3 on 2023-08-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0016_users_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='image',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='payment_id',
            field=models.TextField(default='null', max_length=50),
        ),
    ]
