# Generated by Django 4.2.3 on 2023-09-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0018_users_withdraw_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='prompt_type',
            field=models.TextField(default='free', max_length=5),
        ),
    ]
