# Generated by Django 4.2.3 on 2023-10-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_app', '0019_prompts_prompt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='status',
            field=models.TextField(default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='prompts',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
